apiVersion: v1
kind: Service
metadata:
  name: iris-api-svc
  namespace: ml-course
spec:
  selector:
    app: iris-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
